sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nW2tB76+CofKs88itkeScT04d7bZTbcWMAC+ruuFpd/Um5gC8jFB45qIgF57NHqg6SQ4riHKhOkU8nmRJS6yvFWTDIVFjf5CMNiBn2t7RUAGTgdNyLDDqGTYwGcEtPN2xqEmTsYAg+yqLLffeQmhA+OHIsdtcWLobNW5LNAj/pNXXQCH4bsMbMs25qWjU4WfRdEJaGcu7SpGuHnLd/heuKp9rYmg982d2lieStU/gHZNPz1P0T+jNAVn5KkQwpWT7QSR+4wUnRNg+2GjWfRm110xF8juAMeP+KVEg6ipKPE2/YwLLZwYK7Q0JXqwUiu3LHFpNIUpq5Ikw2xfYvGIkt1ZitWTbwyjCVP7PlqgDt/jy9BhkMM2iF4l7slGj4SPKyKZpAA9xQw75yDlnN48W6tK+3BjlPIo6lBL2JqOq1NfpVDSuAzK0i+2t5aKS7v3trnXsfETTcirYbj4mVJpnJk58eoDIOuHqjdbHF4y5aixlbYxSkvse/qnaEA7SH5GdwGPvzRZUIUKl3+iaCcX3iUSq/Y0hrgKyWZ8KXFyAX9wC27I58NrGg+dDI265SYXnuEQujvI0fC1+xowRFa9ys0yUx2t21wRPfyE28dvjD2YtxgUPY+hBIwVOyx33FgK5uxWY42VS0sBUGQQvVj1Xqaj4NUyWrrdWyop4Sq7aiM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/First-Across-the-Continent--13-The-Story-of-the-Exploring-Expedition-of-Lewis-and-Clark-in-180__1236
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy